# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vibrationtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgb(255, 255, 255);\n"
            "border:0.5px solid black;\n"
            "border-radius:5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    color: rgb(255, 0, 0);\n"
            "}\n"
            "\n"
            "QPushButton:pressed{\n"
            "    padding-bottom:5px;\n"
            "    padding-left:5px;\n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet('font: 75 10pt "ABBvoice CNSG";')
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.serial_number = QtWidgets.QLineEdit(self.frame)
        self.serial_number.setMinimumSize(QtCore.QSize(0, 30))
        self.serial_number.setStyleSheet(
            "border:1px solid black;\n"
            'font: 75 10pt "ABBvoice CNSG";\n'
            "border-radius:5px;"
        )
        self.serial_number.setObjectName("serial_number")
        self.horizontalLayout.addWidget(self.serial_number)
        self.get_serial_number_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.get_serial_number_button.sizePolicy().hasHeightForWidth()
        )
        self.get_serial_number_button.setSizePolicy(sizePolicy)
        self.get_serial_number_button.setMinimumSize(QtCore.QSize(150, 30))
        self.get_serial_number_button.setStyleSheet('font: 75 10pt "ABBvoice CNSG";')
        self.get_serial_number_button.setObjectName("get_serial_number_button")
        self.horizontalLayout.addWidget(self.get_serial_number_button)
        self.verticalLayout.addWidget(self.frame)
        self.status_text = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.status_text.sizePolicy().hasHeightForWidth())
        self.status_text.setSizePolicy(sizePolicy)
        self.status_text.setStyleSheet(
            'font: 9pt "ABBvoice CNSG";\n' "background-color: rgb(255,255,255);\n" ""
        )
        self.status_text.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.status_text.setObjectName("status_text")
        self.verticalLayout.addWidget(self.status_text)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet(
            "QPushButton:hover{\n"
            "    color: rgb(255, 0, 0);\n"
            "}\n"
            "\n"
            "QPushButton:pressed{\n"
            "    padding-bottom:5px;\n"
            "    padding-left:5px;\n"
            "}\n"
            "\n"
            "QPushButton{\n"
            "border:0.5px solid black;\n"
            "    background-color: rgb(255, 255, 255);\n"
            "border-radius:5px;\n"
            'font: 75 10pt "ABBvoice CNSG";\n'
            "}"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viration_test_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.viration_test_button.sizePolicy().hasHeightForWidth()
        )
        self.viration_test_button.setSizePolicy(sizePolicy)
        self.viration_test_button.setMinimumSize(QtCore.QSize(150, 30))
        self.viration_test_button.setStyleSheet("")
        self.viration_test_button.setObjectName("viration_test_button")
        self.horizontalLayout_2.addWidget(self.viration_test_button)
        self.stop_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setMinimumSize(QtCore.QSize(150, 30))
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_2.addWidget(self.stop_button)
        self.gotosyncpose_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gotosyncpose_button.sizePolicy().hasHeightForWidth()
        )
        self.gotosyncpose_button.setSizePolicy(sizePolicy)
        self.gotosyncpose_button.setMinimumSize(QtCore.QSize(150, 30))
        self.gotosyncpose_button.setObjectName("gotosyncpose_button")
        self.horizontalLayout_2.addWidget(self.gotosyncpose_button)
        self.motor_on_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.motor_on_button.sizePolicy().hasHeightForWidth()
        )
        self.motor_on_button.setSizePolicy(sizePolicy)
        self.motor_on_button.setMinimumSize(QtCore.QSize(150, 30))
        self.motor_on_button.setObjectName("motor_on_button")
        self.horizontalLayout_2.addWidget(self.motor_on_button)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Serial NO."))
        self.serial_number.setPlaceholderText(
            _translate("MainWindow", "Input Serial NO., such as: 1100-000001")
        )
        self.get_serial_number_button.setText(
            _translate("MainWindow", "Get Serial NO.")
        )
        self.status_text.setText(_translate("MainWindow", ""))
        self.viration_test_button.setText(_translate("MainWindow", "Vibration Test"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.gotosyncpose_button.setText(_translate("MainWindow", "GotoSyncPos"))
        self.motor_on_button.setText(_translate("MainWindow", "Motor ON"))
